restart-limit: 3
restart-threshold: 10
restart-reset-period: 3
containers-to-watch: ['*thinpoc*', '*tracking-web*', '*tracking-public*', '*tracking-maintenance*', '*docforge*', '*mailcatcher*', '*tracking*nginx*']
notification-email-addresses: ['nsziszy@gmail.com']
notification-email-server: smtp.gmail.com
notification-hostname: testhostname
print-all-events: false