restart-limit: ${RESTART_LIMIT}
restart-threshold: ${RESTART_THRESHOLD}
restart-reset-period: ${RESTART_RESET_PERIOD}
containers-to-watch: ${CONTAINERS_TO_WATCH}
notification-email-addresses: ${NOTIFICATION_EMAIL_ADDRESSES}
notification-email-server: ${NOTIFICATION_EMAIL_SERVER}
print-all-events: ${PRINT_ALL_EVENTS}